### ISSUE TITLE
Getting issue while starting the service.

### ISSUE THREAD

**Issue by ashubhumca** [flipkart-incubator/foxtrot#10]
Hi,

I'm trying to use this foxtrot tool on my local mac machine and have elastic search and Hbase instances up.
But when I try to start service then it is giving below error:

Command:
java -Dfile.encoding=utf-8 -jar foxtrot-server/target/foxtrot-server-0.1.jar server config/local.yml 

Error log:
15/01/02 11:24:49 INFO util.Version: HV000001: Hibernate Validator 4.3.1.Final
Exception in thread "main" com.yammer.dropwizard.config.ConfigurationException: config/local.yml has the following errors:
  * cluster.webServerUrl may not be empty (was null)
  * cluster.webServerUrl may not be null (was null)

	at com.yammer.dropwizard.config.ConfigurationFactory.validate(ConfigurationFactory.java:94)
	at com.yammer.dropwizard.config.ConfigurationFactory.build(ConfigurationFactory.java:64)
	at com.yammer.dropwizard.config.ConfigurationFactory.build(ConfigurationFactory.java:48)
	at com.yammer.dropwizard.cli.ConfiguredCommand.parseConfiguration(ConfiguredCommand.java:83)
	at com.yammer.dropwizard.cli.ConfiguredCommand.run(ConfiguredCommand.java:51)
	at com.yammer.dropwizard.cli.Cli.run(Cli.java:53)
	at com.yammer.dropwizard.Service.run(Service.java:61)
	at com.flipkart.foxtrot.server.App.main(App.java:30)

I might have to modify this local.yml so please describe all the configuration options in the yml file and let me know what I should do to fix this issue.

Thanks in advance.

Regards,
Ashish

**Comment by santanusinha** [comment]
This is fixed. The problem was due to a commit to enable Hazelcast management center. It has been removed for now. We'll implement this properly later. Please pull again.

Also remember to create the named table in hbase to get this to work properly using atleast the following in hbase shell:

create 'foxtrot', 'd'

Here's a working config file:
http:
  port: 18000
  adminPort: 18001
  connectorType: nonblocking

elasticsearch:
  hosts:
  - 127.0.0.1
  cluster: foxtrot-demo

hbase:
  secure : false
  tableName: foxtrot

cluster:
  name: foxtrot
  disableMulticast: true
  members: ["localhost:5701", "localhost:5702"]

logging:
  level: INFO

deletionconfig:
  active: true
  interval: 86400
  initialdelay: 60


Please comment to let us know if this is working for you.

**Comment by santanusinha** [comment]
Also sorry for the late reply, google Inbox was intelligent enough to hide this effectively.

**Comment by ashubhumca** [comment]
Thanks Santanu for the reply.
I've re-cloned the repo and followed your instructions. But still I'm getting below issue:


ashish$ java -Dfile.encoding=utf-8 -jar foxtrot-server/target/foxtrot-server-0.1.jar server config/local.yml 
15/01/05 12:21:57 INFO util.Version: HV000001: Hibernate Validator 4.3.1.Final
INFO  [2015-01-05 06:51:59,550] com.yammer.dropwizard.cli.ServerCommand: Starting foxtrot
INFO  [2015-01-05 06:51:59,553] org.eclipse.jetty.server.Server: jetty-8.y.z-SNAPSHOT
INFO  [2015-01-05 06:51:59,659] com.sun.jersey.server.impl.application.WebApplicationImpl: Initiating Jersey application, version 'Jersey: 1.17.1 02/28/2013 12:47 PM'
INFO  [2015-01-05 06:51:59,760] com.yammer.dropwizard.config.Environment: The following paths were found for the configured resources:

    GET     /foxtrot/v1/document/{table} (com.flipkart.foxtrot.server.resources.DocumentResource)
    GET     /foxtrot/v1/document/{table}/{id} (com.flipkart.foxtrot.server.resources.DocumentResource)
    POST    /foxtrot/v1/document/{table} (com.flipkart.foxtrot.server.resources.DocumentResource)
    POST    /foxtrot/v1/document/{table}/bulk (com.flipkart.foxtrot.server.resources.DocumentResource)
    GET     /foxtrot/v1/async/{action}/{id} (com.flipkart.foxtrot.server.resources.AsyncResource)
    POST    /foxtrot/v1/async (com.flipkart.foxtrot.server.resources.AsyncResource)
    POST    /foxtrot/v1/analytics (com.flipkart.foxtrot.server.resources.AnalyticsResource)
    POST    /foxtrot/v1/analytics/async (com.flipkart.foxtrot.server.resources.AnalyticsResource)
    DELETE  /foxtrot/v1/tables/{name}/delete (com.flipkart.foxtrot.server.resources.TableMetadataResource)
    GET     /foxtrot/v1/tables (com.flipkart.foxtrot.server.resources.TableMetadataResource)
    GET     /foxtrot/v1/tables/{name} (com.flipkart.foxtrot.server.resources.TableMetadataResource)
    POST    /foxtrot/v1/tables (com.flipkart.foxtrot.server.resources.TableMetadataResource)
    GET     /foxtrot/v1/tables/{name}/fields (com.flipkart.foxtrot.server.resources.TableFieldMappingResource)
    DELETE  /foxtrot/v1/consoles/{id}/delete (com.flipkart.foxtrot.server.resources.ConsoleResource)
    GET     /foxtrot/v1/consoles (com.flipkart.foxtrot.server.resources.ConsoleResource)
    GET     /foxtrot/v1/consoles/{id} (com.flipkart.foxtrot.server.resources.ConsoleResource)
    POST    /foxtrot/v1/consoles (com.flipkart.foxtrot.server.resources.ConsoleResource)
    GET     /foxtrot/v1/fql/download (com.flipkart.foxtrot.server.resources.FqlResource)
    POST    /foxtrot/v1/fql (com.flipkart.foxtrot.server.resources.FqlResource)
    GET     /foxtrot/v1/cluster/members (com.flipkart.foxtrot.server.resources.ClusterInfoResource)

INFO  [2015-01-05 06:51:59,760] com.yammer.dropwizard.config.Environment: tasks = 

    POST    /tasks/gc (com.yammer.dropwizard.tasks.GarbageCollectionTask)

INFO  [2015-01-05 06:52:00,149] HbaseTableConnection: Starting HBase Connection
INFO  [2015-01-05 06:52:00,395] HbaseTableConnection: Started HBase Connection
INFO  [2015-01-05 06:52:00,395] ElasticsearchConnection: Starting Elasticsearch Client
15/01/05 12:22:00 INFO elasticsearch.plugins: [Firebrand] loaded [], sites []
15/01/05 12:22:01 WARN client.transport: [Firebrand] node [#transport#-1][Ashoks-MacBook-Pro.local][inet[/127.0.0.1:9300]] not part of the cluster Cluster [foxtrot], ignoring...
INFO  [2015-01-05 06:52:01,073] ElasticsearchConnection: Added Elasticsearch Node : 127.0.0.1
INFO  [2015-01-05 06:52:01,073] ElasticsearchConnection: Started Elasticsearch Client
INFO  [2015-01-05 06:52:01,073] HazelcastConnection: Starting Hazelcast Instance
INFO  [2015-01-05 06:52:01,248] com.hazelcast.instance.DefaultAddressPicker: [LOCAL] [foxtrot] [3.3.3] Resolving domain name 'localhost' to address(es): [127.0.0.1, 0:0:0:0:0:0:0:1, fe80:0:0:0:0:0:0:1%1]
INFO  [2015-01-05 06:52:01,248] com.hazelcast.instance.DefaultAddressPicker: [LOCAL] [foxtrot] [3.3.3] Resolving domain name 'localhost' to address(es): [127.0.0.1, 0:0:0:0:0:0:0:1, fe80:0:0:0:0:0:0:1%1]
INFO  [2015-01-05 06:52:01,249] com.hazelcast.instance.DefaultAddressPicker: [LOCAL] [foxtrot] [3.3.3] Interfaces is disabled, trying to pick one address from TCP-IP config addresses: [localhost/fe80:0:0:0:0:0:0:1%1, localhost/127.0.0.1, localhost/0:0:0:0:0:0:0:1]
INFO  [2015-01-05 06:52:01,249] com.hazelcast.instance.DefaultAddressPicker: [LOCAL] [foxtrot] [3.3.3] Prefer IPv4 stack is true.
INFO  [2015-01-05 06:52:01,258] com.hazelcast.instance.DefaultAddressPicker: [LOCAL] [foxtrot] [3.3.3] Picked Address[localhost]:5701, using socket ServerSocket[addr=/0:0:0:0:0:0:0:0,localport=5701], bind any local is true
INFO  [2015-01-05 06:52:01,282] com.hazelcast.spi.impl.BasicOperationScheduler: [localhost]:5701 [foxtrot] [3.3.3] Starting with 8 generic operation threads and 8 partition operation threads.
INFO  [2015-01-05 06:52:01,358] com.hazelcast.system: [localhost]:5701 [foxtrot] [3.3.3] Hazelcast 3.3.3 (20141112 - eadb69c) starting at Address[localhost]:5701
INFO  [2015-01-05 06:52:01,358] com.hazelcast.system: [localhost]:5701 [foxtrot] [3.3.3] Copyright (C) 2008-2014 Hazelcast.com
INFO  [2015-01-05 06:52:01,359] com.hazelcast.instance.Node: [localhost]:5701 [foxtrot] [3.3.3] Creating TcpIpJoiner
INFO  [2015-01-05 06:52:01,360] com.hazelcast.core.LifecycleService: [localhost]:5701 [foxtrot] [3.3.3] Address[localhost]:5701 is STARTING
INFO  [2015-01-05 06:52:01,432] com.hazelcast.nio.tcp.SocketConnector: [localhost]:5701 [foxtrot] [3.3.3] Connecting to localhost/127.0.0.1:5702, timeout: 0, bind-any: true
INFO  [2015-01-05 06:52:01,433] com.hazelcast.nio.tcp.SocketConnector: [localhost]:5701 [foxtrot] [3.3.3] Could not connect to: localhost/127.0.0.1:5702. Reason: SocketException[Connection refused to address localhost/127.0.0.1:5702]
INFO  [2015-01-05 06:52:01,433] com.hazelcast.cluster.TcpIpJoiner: [localhost]:5701 [foxtrot] [3.3.3] Address[localhost]:5702 is added to the blacklist.
INFO  [2015-01-05 06:52:02,439] com.hazelcast.cluster.TcpIpJoiner: [localhost]:5701 [foxtrot] [3.3.3] 


Members [1] {
	Member [localhost]:5701 this
}

INFO  [2015-01-05 06:52:02,466] com.hazelcast.core.LifecycleService: [localhost]:5701 [foxtrot] [3.3.3] Address[localhost]:5701 is STARTED
INFO  [2015-01-05 06:52:02,467] HazelcastConnection: Started Hazelcast Instance
INFO  [2015-01-05 06:52:02,491] TableMapStore: Load all keys called
WARN  [2015-01-05 06:52:02,525] org.eclipse.jetty.util.component.AbstractLifeCycle: FAILED com.flipkart.foxtrot.core.querystore.impl.DistributedTableMetadataManager@625eaad8: org.elasticsearch.client.transport.NoNodeAvailableException: No node available
! org.elasticsearch.client.transport.NoNodeAvailableException: No node available
! at org.elasticsearch.client.transport.TransportClientNodesService.execute(TransportClientNodesService.java:219) ~[foxtrot-server-0.1.jar:na]
! at org.elasticsearch.client.transport.support.InternalTransportClient.execute(InternalTransportClient.java:106) ~[foxtrot-server-0.1.jar:na]
! at org.elasticsearch.client.support.AbstractClient.search(AbstractClient.java:212) ~[foxtrot-server-0.1.jar:na]
! at org.elasticsearch.client.transport.TransportClient.search(TransportClient.java:420) ~[foxtrot-server-0.1.jar:na]
! at org.elasticsearch.action.search.SearchRequestBuilder.doExecute(SearchRequestBuilder.java:1043) ~[foxtrot-server-0.1.jar:na]
! at org.elasticsearch.action.ActionRequestBuilder.execute(ActionRequestBuilder.java:85) ~[foxtrot-server-0.1.jar:na]
! at org.elasticsearch.action.ActionRequestBuilder.execute(ActionRequestBuilder.java:59) ~[foxtrot-server-0.1.jar:na]
! at com.flipkart.foxtrot.core.querystore.impl.TableMapStore.loadAllKeys(TableMapStore.java:196) ~[foxtrot-server-0.1.jar:na]
! at com.hazelcast.map.MapStoreWrapper.loadAllKeys(MapStoreWrapper.java:114) ~[foxtrot-server-0.1.jar:na]
! at com.hazelcast.map.MapContainer.loadInitialKeys(MapContainer.java:203) ~[foxtrot-server-0.1.jar:na]
! at com.hazelcast.map.MapContainer.initMapStore(MapContainer.java:169) ~[foxtrot-server-0.1.jar:na]
! at com.hazelcast.map.MapContainer.initMapStoreOperations(MapContainer.java:114) ~[foxtrot-server-0.1.jar:na]
! at com.hazelcast.map.MapContainer.<init>(MapContainer.java:83) ~[foxtrot-server-0.1.jar:na]
! at com.hazelcast.map.DefaultMapServiceContext$1.createNew(DefaultMapServiceContext.java:33) ~[foxtrot-server-0.1.jar:na]
! at com.hazelcast.map.DefaultMapServiceContext$1.createNew(DefaultMapServiceContext.java:31) ~[foxtrot-server-0.1.jar:na]
! at com.hazelcast.util.ConcurrencyUtil.getOrPutSynchronized(ConcurrencyUtil.java:40) ~[foxtrot-server-0.1.jar:na]
! at com.hazelcast.map.DefaultMapServiceContext.getMapContainer(DefaultMapServiceContext.java:71) ~[foxtrot-server-0.1.jar:na]
! at com.hazelcast.map.proxy.MapProxySupport.<init>(MapProxySupport.java:140) ~[foxtrot-server-0.1.jar:na]
! at com.hazelcast.map.proxy.MapProxyImpl.<init>(MapProxyImpl.java:75) ~[foxtrot-server-0.1.jar:na]
! at com.hazelcast.map.MapRemoteService.createDistributedObject(MapRemoteService.java:26) ~[foxtrot-server-0.1.jar:na]
! at com.hazelcast.map.MapRemoteService.createDistributedObject(MapRemoteService.java:14) ~[foxtrot-server-0.1.jar:na]
! at com.hazelcast.map.MapService.createDistributedObject(MapService.java:126) ~[foxtrot-server-0.1.jar:na]
! at com.hazelcast.spi.impl.ProxyServiceImpl$ProxyRegistry.createProxy(ProxyServiceImpl.java:336) ~[foxtrot-server-0.1.jar:na]
! at com.hazelcast.spi.impl.ProxyServiceImpl$ProxyRegistry.getOrCreateProxy(ProxyServiceImpl.java:310) ~[foxtrot-server-0.1.jar:na]
! at com.hazelcast.spi.impl.ProxyServiceImpl.getDistributedObject(ProxyServiceImpl.java:131) ~[foxtrot-server-0.1.jar:na]
! at com.hazelcast.instance.HazelcastInstanceImpl.getDistributedObject(HazelcastInstanceImpl.java:388) ~[foxtrot-server-0.1.jar:na]
! at com.hazelcast.instance.HazelcastInstanceImpl.getMap(HazelcastInstanceImpl.java:176) ~[foxtrot-server-0.1.jar:na]
! at com.hazelcast.instance.HazelcastInstanceProxy.getMap(HazelcastInstanceProxy.java:71) ~[foxtrot-server-0.1.jar:na]
! at com.flipkart.foxtrot.core.querystore.impl.DistributedTableMetadataManager.start(DistributedTableMetadataManager.java:105) ~[foxtrot-server-0.1.jar:na]
! at com.yammer.dropwizard.jetty.JettyManaged.doStart(JettyManaged.java:24) ~[foxtrot-server-0.1.jar:na]
! at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:64) [foxtrot-server-0.1.jar:na]
! at org.eclipse.jetty.util.component.AggregateLifeCycle.doStart(AggregateLifeCycle.java:81) [foxtrot-server-0.1.jar:na]
! at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:64) [foxtrot-server-0.1.jar:na]
! at com.yammer.dropwizard.config.Environment.doStart(Environment.java:116) [foxtrot-server-0.1.jar:na]
! at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:64) [foxtrot-server-0.1.jar:na]
! at org.eclipse.jetty.util.component.AggregateLifeCycle.doStart(AggregateLifeCycle.java:81) [foxtrot-server-0.1.jar:na]
! at org.eclipse.jetty.server.handler.AbstractHandler.doStart(AbstractHandler.java:58) [foxtrot-server-0.1.jar:na]
! at org.eclipse.jetty.server.handler.HandlerWrapper.doStart(HandlerWrapper.java:96) [foxtrot-server-0.1.jar:na]
! at org.eclipse.jetty.server.Server.doStart(Server.java:280) [foxtrot-server-0.1.jar:na]
! at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:64) [foxtrot-server-0.1.jar:na]
! at com.yammer.dropwizard.cli.ServerCommand.run(ServerCommand.java:48) [foxtrot-server-0.1.jar:na]
! at com.yammer.dropwizard.cli.EnvironmentCommand.run(EnvironmentCommand.java:39) [foxtrot-server-0.1.jar:na]
! at com.yammer.dropwizard.cli.ConfiguredCommand.run(ConfiguredCommand.java:58) [foxtrot-server-0.1.jar:na]
! at com.yammer.dropwizard.cli.Cli.run(Cli.java:53) [foxtrot-server-0.1.jar:na]
! at com.yammer.dropwizard.Service.run(Service.java:61) [foxtrot-server-0.1.jar:na]
! at com.flipkart.foxtrot.server.App.main(App.java:30) [foxtrot-server-0.1.jar:na]
WARN  [2015-01-05 06:52:02,526] org.eclipse.jetty.util.component.AbstractLifeCycle: FAILED org.eclipse.jetty.util.component.AggregateLifeCycle@66ac601c: org.elasticsearch.client.transport.NoNodeAvailableException: No node available
! org.elasticsearch.client.transport.NoNodeAvailableException: No node available
! at org.elasticsearch.client.transport.TransportClientNodesService.execute(TransportClientNodesService.java:219) ~[foxtrot-server-0.1.jar:na]
! at org.elasticsearch.client.transport.support.InternalTransportClient.execute(InternalTransportClient.java:106) ~[foxtrot-server-0.1.jar:na]
! at org.elasticsearch.client.support.AbstractClient.search(AbstractClient.java:212) ~[foxtrot-server-0.1.jar:na]
! at org.elasticsearch.client.transport.TransportClient.search(TransportClient.java:420) ~[foxtrot-server-0.1.jar:na]
! at org.elasticsearch.action.search.SearchRequestBuilder.doExecute(SearchRequestBuilder.java:1043) ~[foxtrot-server-0.1.jar:na]
! at org.elasticsearch.action.ActionRequestBuilder.execute(ActionRequestBuilder.java:85) ~[foxtrot-server-0.1.jar:na]
! at org.elasticsearch.action.ActionRequestBuilder.execute(ActionRequestBuilder.java:59) ~[foxtrot-server-0.1.jar:na]
! at com.flipkart.foxtrot.core.querystore.impl.TableMapStore.loadAllKeys(TableMapStore.java:196) ~[foxtrot-server-0.1.jar:na]
! at com.hazelcast.map.MapStoreWrapper.loadAllKeys(MapStoreWrapper.java:114) ~[foxtrot-server-0.1.jar:na]
! at com.hazelcast.map.MapContainer.loadInitialKeys(MapContainer.java:203) ~[foxtrot-server-0.1.jar:na]
! at com.hazelcast.map.MapContainer.initMapStore(MapContainer.java:169) ~[foxtrot-server-0.1.jar:na]
! at com.hazelcast.map.MapContainer.initMapStoreOperations(MapContainer.java:114) ~[foxtrot-server-0.1.jar:na]
! at com.hazelcast.map.MapContainer.<init>(MapContainer.java:83) ~[foxtrot-server-0.1.jar:na]
! at com.hazelcast.map.DefaultMapServiceContext$1.createNew(DefaultMapServiceContext.java:33) ~[foxtrot-server-0.1.jar:na]
! at com.hazelcast.map.DefaultMapServiceContext$1.createNew(DefaultMapServiceContext.java:31) ~[foxtrot-server-0.1.jar:na]
! at com.hazelcast.util.ConcurrencyUtil.getOrPutSynchronized(ConcurrencyUtil.java:40) ~[foxtrot-server-0.1.jar:na]
! at com.hazelcast.map.DefaultMapServiceContext.getMapContainer(DefaultMapServiceContext.java:71) ~[foxtrot-server-0.1.jar:na]
! at com.hazelcast.map.proxy.MapProxySupport.<init>(MapProxySupport.java:140) ~[foxtrot-server-0.1.jar:na]
! at com.hazelcast.map.proxy.MapProxyImpl.<init>(MapProxyImpl.java:75) ~[foxtrot-server-0.1.jar:na]
! at com.hazelcast.map.MapRemoteService.createDistributedObject(MapRemoteService.java:26) ~[foxtrot-server-0.1.jar:na]
! at com.hazelcast.map.MapRemoteService.createDistributedObject(MapRemoteService.java:14) ~[foxtrot-server-0.1.jar:na]
! at com.hazelcast.map.MapService.createDistributedObject(MapService.java:126) ~[foxtrot-server-0.1.jar:na]
! at com.hazelcast.spi.impl.ProxyServiceImpl$ProxyRegistry.createProxy(ProxyServiceImpl.java:336) ~[foxtrot-server-0.1.jar:na]
! at com.hazelcast.spi.impl.ProxyServiceImpl$ProxyRegistry.getOrCreateProxy(ProxyServiceImpl.java:310) ~[foxtrot-server-0.1.jar:na]
! at com.hazelcast.spi.impl.ProxyServiceImpl.getDistributedObject(ProxyServiceImpl.java:131) ~[foxtrot-server-0.1.jar:na]
! at com.hazelcast.instance.HazelcastInstanceImpl.getDistributedObject(HazelcastInstanceImpl.java:388) ~[foxtrot-server-0.1.jar:na]
! at com.hazelcast.instance.HazelcastInstanceImpl.getMap(HazelcastInstanceImpl.java:176) ~[foxtrot-server-0.1.jar:na]
! at com.hazelcast.instance.HazelcastInstanceProxy.getMap(HazelcastInstanceProxy.java:71) ~[foxtrot-server-0.1.jar:na]
! at com.flipkart.foxtrot.core.querystore.impl.DistributedTableMetadataManager.start(DistributedTableMetadataManager.java:105) ~[foxtrot-server-0.1.jar:na]
! at com.yammer.dropwizard.jetty.JettyManaged.doStart(JettyManaged.java:24) ~[foxtrot-server-0.1.jar:na]
! at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:64) [foxtrot-server-0.1.jar:na]
! at org.eclipse.jetty.util.component.AggregateLifeCycle.doStart(AggregateLifeCycle.java:81) [foxtrot-server-0.1.jar:na]
! at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:64) [foxtrot-server-0.1.jar:na]
! at com.yammer.dropwizard.config.Environment.doStart(Environment.java:116) [foxtrot-server-0.1.jar:na]
! at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:64) [foxtrot-server-0.1.jar:na]
! at org.eclipse.jetty.util.component.AggregateLifeCycle.doStart(AggregateLifeCycle.java:81) [foxtrot-server-0.1.jar:na]
! at org.eclipse.jetty.server.handler.AbstractHandler.doStart(AbstractHandler.java:58) [foxtrot-server-0.1.jar:na]
! at org.eclipse.jetty.server.handler.HandlerWrapper.doStart(HandlerWrapper.java:96) [foxtrot-server-0.1.jar:na]
! at org.eclipse.jetty.server.Server.doStart(Server.java:280) [foxtrot-server-0.1.jar:na]
! at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:64) [foxtrot-server-0.1.jar:na]
! at com.yammer.dropwizard.cli.ServerCommand.run(ServerCommand.java:48) [foxtrot-server-0.1.jar:na]
! at com.yammer.dropwizard.cli.EnvironmentCommand.run(EnvironmentCommand.java:39) [foxtrot-server-0.1.jar:na]
! at com.yammer.dropwizard.cli.ConfiguredCommand.run(ConfiguredCommand.java:58) [foxtrot-server-0.1.jar:na]
! at com.yammer.dropwizard.cli.Cli.run(Cli.java:53) [foxtrot-server-0.1.jar:na]
! at com.yammer.dropwizard.Service.run(Service.java:61) [foxtrot-server-0.1.jar:na]
! at com.flipkart.foxtrot.server.App.main(App.java:30) [foxtrot-server-0.1.jar:na]
WARN  [2015-01-05 06:52:02,527] org.eclipse.jetty.util.component.AbstractLifeCycle: FAILED com.yammer.dropwizard.config.Environment@3eda02ed: org.elasticsearch.client.transport.NoNodeAvailableException: No node available
! org.elasticsearch.client.transport.NoNodeAvailableException: No node available
! at org.elasticsearch.client.transport.TransportClientNodesService.execute(TransportClientNodesService.java:219) ~[foxtrot-server-0.1.jar:na]
! at org.elasticsearch.client.transport.support.InternalTransportClient.execute(InternalTransportClient.java:106) ~[foxtrot-server-0.1.jar:na]
! at org.elasticsearch.client.support.AbstractClient.search(AbstractClient.java:212) ~[foxtrot-server-0.1.jar:na]
! at org.elasticsearch.client.transport.TransportClient.search(TransportClient.java:420) ~[foxtrot-server-0.1.jar:na]
! at org.elasticsearch.action.search.SearchRequestBuilder.doExecute(SearchRequestBuilder.java:1043) ~[foxtrot-server-0.1.jar:na]
! at org.elasticsearch.action.ActionRequestBuilder.execute(ActionRequestBuilder.java:85) ~[foxtrot-server-0.1.jar:na]
! at org.elasticsearch.action.ActionRequestBuilder.execute(ActionRequestBuilder.java:59) ~[foxtrot-server-0.1.jar:na]
! at com.flipkart.foxtrot.core.querystore.impl.TableMapStore.loadAllKeys(TableMapStore.java:196) ~[foxtrot-server-0.1.jar:na]
! at com.hazelcast.map.MapStoreWrapper.loadAllKeys(MapStoreWrapper.java:114) ~[foxtrot-server-0.1.jar:na]
! at com.hazelcast.map.MapContainer.loadInitialKeys(MapContainer.java:203) ~[foxtrot-server-0.1.jar:na]
! at com.hazelcast.map.MapContainer.initMapStore(MapContainer.java:169) ~[foxtrot-server-0.1.jar:na]
! at com.hazelcast.map.MapContainer.initMapStoreOperations(MapContainer.java:114) ~[foxtrot-server-0.1.jar:na]
! at com.hazelcast.map.MapContainer.<init>(MapContainer.java:83) ~[foxtrot-server-0.1.jar:na]
! at com.hazelcast.map.DefaultMapServiceContext$1.createNew(DefaultMapServiceContext.java:33) ~[foxtrot-server-0.1.jar:na]
! at com.hazelcast.map.DefaultMapServiceContext$1.createNew(DefaultMapServiceContext.java:31) ~[foxtrot-server-0.1.jar:na]
! at com.hazelcast.util.ConcurrencyUtil.getOrPutSynchronized(ConcurrencyUtil.java:40) ~[foxtrot-server-0.1.jar:na]
! at com.hazelcast.map.DefaultMapServiceContext.getMapContainer(DefaultMapServiceContext.java:71) ~[foxtrot-server-0.1.jar:na]
! at com.hazelcast.map.proxy.MapProxySupport.<init>(MapProxySupport.java:140) ~[foxtrot-server-0.1.jar:na]
! at com.hazelcast.map.proxy.MapProxyImpl.<init>(MapProxyImpl.java:75) ~[foxtrot-server-0.1.jar:na]
! at com.hazelcast.map.MapRemoteService.createDistributedObject(MapRemoteService.java:26) ~[foxtrot-server-0.1.jar:na]
! at com.hazelcast.map.MapRemoteService.createDistributedObject(MapRemoteService.java:14) ~[foxtrot-server-0.1.jar:na]
! at com.hazelcast.map.MapService.createDistributedObject(MapService.java:126) ~[foxtrot-server-0.1.jar:na]
! at com.hazelcast.spi.impl.ProxyServiceImpl$ProxyRegistry.createProxy(ProxyServiceImpl.java:336) ~[foxtrot-server-0.1.jar:na]
! at com.hazelcast.spi.impl.ProxyServiceImpl$ProxyRegistry.getOrCreateProxy(ProxyServiceImpl.java:310) ~[foxtrot-server-0.1.jar:na]
! at com.hazelcast.spi.impl.ProxyServiceImpl.getDistributedObject(ProxyServiceImpl.java:131) ~[foxtrot-server-0.1.jar:na]
! at com.hazelcast.instance.HazelcastInstanceImpl.getDistributedObject(HazelcastInstanceImpl.java:388) ~[foxtrot-server-0.1.jar:na]
! at com.hazelcast.instance.HazelcastInstanceImpl.getMap(HazelcastInstanceImpl.java:176) ~[foxtrot-server-0.1.jar:na]
! at com.hazelcast.instance.HazelcastInstanceProxy.getMap(HazelcastInstanceProxy.java:71) ~[foxtrot-server-0.1.jar:na]
! at com.flipkart.foxtrot.core.querystore.impl.DistributedTableMetadataManager.start(DistributedTableMetadataManager.java:105) ~[foxtrot-server-0.1.jar:na]
! at com.yammer.dropwizard.jetty.JettyManaged.doStart(JettyManaged.java:24) ~[foxtrot-server-0.1.jar:na]
! at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:64) [foxtrot-server-0.1.jar:na]
! at org.eclipse.jetty.util.component.AggregateLifeCycle.doStart(AggregateLifeCycle.java:81) [foxtrot-server-0.1.jar:na]
! at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:64) [foxtrot-server-0.1.jar:na]
! at com.yammer.dropwizard.config.Environment.doStart(Environment.java:116) ~[foxtrot-server-0.1.jar:na]
! at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:64) [foxtrot-server-0.1.jar:na]
! at org.eclipse.jetty.util.component.AggregateLifeCycle.doStart(AggregateLifeCycle.java:81) [foxtrot-server-0.1.jar:na]
! at org.eclipse.jetty.server.handler.AbstractHandler.doStart(AbstractHandler.java:58) [foxtrot-server-0.1.jar:na]
! at org.eclipse.jetty.server.handler.HandlerWrapper.doStart(HandlerWrapper.java:96) [foxtrot-server-0.1.jar:na]
! at org.eclipse.jetty.server.Server.doStart(Server.java:280) [foxtrot-server-0.1.jar:na]
! at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:64) [foxtrot-server-0.1.jar:na]
! at com.yammer.dropwizard.cli.ServerCommand.run(ServerCommand.java:48) [foxtrot-server-0.1.jar:na]
! at com.yammer.dropwizard.cli.EnvironmentCommand.run(EnvironmentCommand.java:39) [foxtrot-server-0.1.jar:na]
! at com.yammer.dropwizard.cli.ConfiguredCommand.run(ConfiguredCommand.java:58) [foxtrot-server-0.1.jar:na]
! at com.yammer.dropwizard.cli.Cli.run(Cli.java:53) [foxtrot-server-0.1.jar:na]
! at com.yammer.dropwizard.Service.run(Service.java:61) [foxtrot-server-0.1.jar:na]
! at com.flipkart.foxtrot.server.App.main(App.java:30) [foxtrot-server-0.1.jar:na]
WARN  [2015-01-05 06:52:02,528] org.eclipse.jetty.util.component.AbstractLifeCycle: FAILED org.eclipse.jetty.server.Server@5af635d7: org.elasticsearch.client.transport.NoNodeAvailableException: No node available
! org.elasticsearch.client.transport.NoNodeAvailableException: No node available
! at org.elasticsearch.client.transport.TransportClientNodesService.execute(TransportClientNodesService.java:219) ~[foxtrot-server-0.1.jar:na]
! at org.elasticsearch.client.transport.support.InternalTransportClient.execute(InternalTransportClient.java:106) ~[foxtrot-server-0.1.jar:na]
! at org.elasticsearch.client.support.AbstractClient.search(AbstractClient.java:212) ~[foxtrot-server-0.1.jar:na]
! at org.elasticsearch.client.transport.TransportClient.search(TransportClient.java:420) ~[foxtrot-server-0.1.jar:na]
! at org.elasticsearch.action.search.SearchRequestBuilder.doExecute(SearchRequestBuilder.java:1043) ~[foxtrot-server-0.1.jar:na]
! at org.elasticsearch.action.ActionRequestBuilder.execute(ActionRequestBuilder.java:85) ~[foxtrot-server-0.1.jar:na]
! at org.elasticsearch.action.ActionRequestBuilder.execute(ActionRequestBuilder.java:59) ~[foxtrot-server-0.1.jar:na]
! at com.flipkart.foxtrot.core.querystore.impl.TableMapStore.loadAllKeys(TableMapStore.java:196) ~[foxtrot-server-0.1.jar:na]
! at com.hazelcast.map.MapStoreWrapper.loadAllKeys(MapStoreWrapper.java:114) ~[foxtrot-server-0.1.jar:na]
! at com.hazelcast.map.MapContainer.loadInitialKeys(MapContainer.java:203) ~[foxtrot-server-0.1.jar:na]
! at com.hazelcast.map.MapContainer.initMapStore(MapContainer.java:169) ~[foxtrot-server-0.1.jar:na]
! at com.hazelcast.map.MapContainer.initMapStoreOperations(MapContainer.java:114) ~[foxtrot-server-0.1.jar:na]
! at com.hazelcast.map.MapContainer.<init>(MapContainer.java:83) ~[foxtrot-server-0.1.jar:na]
! at com.hazelcast.map.DefaultMapServiceContext$1.createNew(DefaultMapServiceContext.java:33) ~[foxtrot-server-0.1.jar:na]
! at com.hazelcast.map.DefaultMapServiceContext$1.createNew(DefaultMapServiceContext.java:31) ~[foxtrot-server-0.1.jar:na]
! at com.hazelcast.util.ConcurrencyUtil.getOrPutSynchronized(ConcurrencyUtil.java:40) ~[foxtrot-server-0.1.jar:na]
! at com.hazelcast.map.DefaultMapServiceContext.getMapContainer(DefaultMapServiceContext.java:71) ~[foxtrot-server-0.1.jar:na]
! at com.hazelcast.map.proxy.MapProxySupport.<init>(MapProxySupport.java:140) ~[foxtrot-server-0.1.jar:na]
! at com.hazelcast.map.proxy.MapProxyImpl.<init>(MapProxyImpl.java:75) ~[foxtrot-server-0.1.jar:na]
! at com.hazelcast.map.MapRemoteService.createDistributedObject(MapRemoteService.java:26) ~[foxtrot-server-0.1.jar:na]
! at com.hazelcast.map.MapRemoteService.createDistributedObject(MapRemoteService.java:14) ~[foxtrot-server-0.1.jar:na]
! at com.hazelcast.map.MapService.createDistributedObject(MapService.java:126) ~[foxtrot-server-0.1.jar:na]
! at com.hazelcast.spi.impl.ProxyServiceImpl$ProxyRegistry.createProxy(ProxyServiceImpl.java:336) ~[foxtrot-server-0.1.jar:na]
! at com.hazelcast.spi.impl.ProxyServiceImpl$ProxyRegistry.getOrCreateProxy(ProxyServiceImpl.java:310) ~[foxtrot-server-0.1.jar:na]
! at com.hazelcast.spi.impl.ProxyServiceImpl.getDistributedObject(ProxyServiceImpl.java:131) ~[foxtrot-server-0.1.jar:na]
! at com.hazelcast.instance.HazelcastInstanceImpl.getDistributedObject(HazelcastInstanceImpl.java:388) ~[foxtrot-server-0.1.jar:na]
! at com.hazelcast.instance.HazelcastInstanceImpl.getMap(HazelcastInstanceImpl.java:176) ~[foxtrot-server-0.1.jar:na]
! at com.hazelcast.instance.HazelcastInstanceProxy.getMap(HazelcastInstanceProxy.java:71) ~[foxtrot-server-0.1.jar:na]
! at com.flipkart.foxtrot.core.querystore.impl.DistributedTableMetadataManager.start(DistributedTableMetadataManager.java:105) ~[foxtrot-server-0.1.jar:na]
! at com.yammer.dropwizard.jetty.JettyManaged.doStart(JettyManaged.java:24) ~[foxtrot-server-0.1.jar:na]
! at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:64) ~[foxtrot-server-0.1.jar:na]
! at org.eclipse.jetty.util.component.AggregateLifeCycle.doStart(AggregateLifeCycle.java:81) ~[foxtrot-server-0.1.jar:na]
! at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:64) ~[foxtrot-server-0.1.jar:na]
! at com.yammer.dropwizard.config.Environment.doStart(Environment.java:116) ~[foxtrot-server-0.1.jar:na]
! at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:64) ~[foxtrot-server-0.1.jar:na]
! at org.eclipse.jetty.util.component.AggregateLifeCycle.doStart(AggregateLifeCycle.java:81) ~[foxtrot-server-0.1.jar:na]
! at org.eclipse.jetty.server.handler.AbstractHandler.doStart(AbstractHandler.java:58) ~[foxtrot-server-0.1.jar:na]
! at org.eclipse.jetty.server.handler.HandlerWrapper.doStart(HandlerWrapper.java:96) ~[foxtrot-server-0.1.jar:na]
! at org.eclipse.jetty.server.Server.doStart(Server.java:280) ~[foxtrot-server-0.1.jar:na]
! at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:64) ~[foxtrot-server-0.1.jar:na]
! at com.yammer.dropwizard.cli.ServerCommand.run(ServerCommand.java:48) [foxtrot-server-0.1.jar:na]
! at com.yammer.dropwizard.cli.EnvironmentCommand.run(EnvironmentCommand.java:39) [foxtrot-server-0.1.jar:na]
! at com.yammer.dropwizard.cli.ConfiguredCommand.run(ConfiguredCommand.java:58) [foxtrot-server-0.1.jar:na]
! at com.yammer.dropwizard.cli.Cli.run(Cli.java:53) [foxtrot-server-0.1.jar:na]
! at com.yammer.dropwizard.Service.run(Service.java:61) [foxtrot-server-0.1.jar:na]
! at com.flipkart.foxtrot.server.App.main(App.java:30) [foxtrot-server-0.1.jar:na]
ERROR [2015-01-05 06:52:02,528] com.yammer.dropwizard.cli.ServerCommand: Unable to start server, shutting down
! org.elasticsearch.client.transport.NoNodeAvailableException: No node available
! at org.elasticsearch.client.transport.TransportClientNodesService.execute(TransportClientNodesService.java:219) ~[foxtrot-server-0.1.jar:na]
! at org.elasticsearch.client.transport.support.InternalTransportClient.execute(InternalTransportClient.java:106) ~[foxtrot-server-0.1.jar:na]
! at org.elasticsearch.client.support.AbstractClient.search(AbstractClient.java:212) ~[foxtrot-server-0.1.jar:na]
! at org.elasticsearch.client.transport.TransportClient.search(TransportClient.java:420) ~[foxtrot-server-0.1.jar:na]
! at org.elasticsearch.action.search.SearchRequestBuilder.doExecute(SearchRequestBuilder.java:1043) ~[foxtrot-server-0.1.jar:na]
! at org.elasticsearch.action.ActionRequestBuilder.execute(ActionRequestBuilder.java:85) ~[foxtrot-server-0.1.jar:na]
! at org.elasticsearch.action.ActionRequestBuilder.execute(ActionRequestBuilder.java:59) ~[foxtrot-server-0.1.jar:na]
! at com.flipkart.foxtrot.core.querystore.impl.TableMapStore.loadAllKeys(TableMapStore.java:196) ~[foxtrot-server-0.1.jar:na]
! at com.hazelcast.map.MapStoreWrapper.loadAllKeys(MapStoreWrapper.java:114) ~[foxtrot-server-0.1.jar:na]
! at com.hazelcast.map.MapContainer.loadInitialKeys(MapContainer.java:203) ~[foxtrot-server-0.1.jar:na]
! at com.hazelcast.map.MapContainer.initMapStore(MapContainer.java:169) ~[foxtrot-server-0.1.jar:na]
! at com.hazelcast.map.MapContainer.initMapStoreOperations(MapContainer.java:114) ~[foxtrot-server-0.1.jar:na]
! at com.hazelcast.map.MapContainer.<init>(MapContainer.java:83) ~[foxtrot-server-0.1.jar:na]
! at com.hazelcast.map.DefaultMapServiceContext$1.createNew(DefaultMapServiceContext.java:33) ~[foxtrot-server-0.1.jar:na]
! at com.hazelcast.map.DefaultMapServiceContext$1.createNew(DefaultMapServiceContext.java:31) ~[foxtrot-server-0.1.jar:na]
! at com.hazelcast.util.ConcurrencyUtil.getOrPutSynchronized(ConcurrencyUtil.java:40) ~[foxtrot-server-0.1.jar:na]
! at com.hazelcast.map.DefaultMapServiceContext.getMapContainer(DefaultMapServiceContext.java:71) ~[foxtrot-server-0.1.jar:na]
! at com.hazelcast.map.proxy.MapProxySupport.<init>(MapProxySupport.java:140) ~[foxtrot-server-0.1.jar:na]
! at com.hazelcast.map.proxy.MapProxyImpl.<init>(MapProxyImpl.java:75) ~[foxtrot-server-0.1.jar:na]
! at com.hazelcast.map.MapRemoteService.createDistributedObject(MapRemoteService.java:26) ~[foxtrot-server-0.1.jar:na]
! at com.hazelcast.map.MapRemoteService.createDistributedObject(MapRemoteService.java:14) ~[foxtrot-server-0.1.jar:na]
! at com.hazelcast.map.MapService.createDistributedObject(MapService.java:126) ~[foxtrot-server-0.1.jar:na]
! at com.hazelcast.spi.impl.ProxyServiceImpl$ProxyRegistry.createProxy(ProxyServiceImpl.java:336) ~[foxtrot-server-0.1.jar:na]
! at com.hazelcast.spi.impl.ProxyServiceImpl$ProxyRegistry.getOrCreateProxy(ProxyServiceImpl.java:310) ~[foxtrot-server-0.1.jar:na]
! at com.hazelcast.spi.impl.ProxyServiceImpl.getDistributedObject(ProxyServiceImpl.java:131) ~[foxtrot-server-0.1.jar:na]
! at com.hazelcast.instance.HazelcastInstanceImpl.getDistributedObject(HazelcastInstanceImpl.java:388) ~[foxtrot-server-0.1.jar:na]
! at com.hazelcast.instance.HazelcastInstanceImpl.getMap(HazelcastInstanceImpl.java:176) ~[foxtrot-server-0.1.jar:na]
! at com.hazelcast.instance.HazelcastInstanceProxy.getMap(HazelcastInstanceProxy.java:71) ~[foxtrot-server-0.1.jar:na]
! at com.flipkart.foxtrot.core.querystore.impl.DistributedTableMetadataManager.start(DistributedTableMetadataManager.java:105) ~[foxtrot-server-0.1.jar:na]
! at com.yammer.dropwizard.jetty.JettyManaged.doStart(JettyManaged.java:24) ~[foxtrot-server-0.1.jar:na]
! at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:64) ~[foxtrot-server-0.1.jar:na]
! at org.eclipse.jetty.util.component.AggregateLifeCycle.doStart(AggregateLifeCycle.java:81) ~[foxtrot-server-0.1.jar:na]
! at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:64) ~[foxtrot-server-0.1.jar:na]
! at com.yammer.dropwizard.config.Environment.doStart(Environment.java:116) ~[foxtrot-server-0.1.jar:na]
! at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:64) ~[foxtrot-server-0.1.jar:na]
! at org.eclipse.jetty.util.component.AggregateLifeCycle.doStart(AggregateLifeCycle.java:81) ~[foxtrot-server-0.1.jar:na]
! at org.eclipse.jetty.server.handler.AbstractHandler.doStart(AbstractHandler.java:58) ~[foxtrot-server-0.1.jar:na]
! at org.eclipse.jetty.server.handler.HandlerWrapper.doStart(HandlerWrapper.java:96) ~[foxtrot-server-0.1.jar:na]
! at org.eclipse.jetty.server.Server.doStart(Server.java:280) ~[foxtrot-server-0.1.jar:na]
! at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:64) ~[foxtrot-server-0.1.jar:na]
! at com.yammer.dropwizard.cli.ServerCommand.run(ServerCommand.java:48) ~[foxtrot-server-0.1.jar:na]
! at com.yammer.dropwizard.cli.EnvironmentCommand.run(EnvironmentCommand.java:39) [foxtrot-server-0.1.jar:na]
! at com.yammer.dropwizard.cli.ConfiguredCommand.run(ConfiguredCommand.java:58) [foxtrot-server-0.1.jar:na]
! at com.yammer.dropwizard.cli.Cli.run(Cli.java:53) [foxtrot-server-0.1.jar:na]
! at com.yammer.dropwizard.Service.run(Service.java:61) [foxtrot-server-0.1.jar:na]
! at com.flipkart.foxtrot.server.App.main(App.java:30) [foxtrot-server-0.1.jar:na]
INFO  [2015-01-05 06:52:02,529] org.eclipse.jetty.server.Server: Graceful shutdown SocketConnector@0.0.0.0:18001
INFO  [2015-01-05 06:52:02,529] org.eclipse.jetty.server.Server: Graceful shutdown InstrumentedSelectChannelConnector@0.0.0.0:18000
INFO  [2015-01-05 06:52:02,529] org.eclipse.jetty.server.Server: Graceful shutdown o.e.j.s.ServletContextHandler{/,null}
INFO  [2015-01-05 06:52:02,529] org.eclipse.jetty.server.Server: Graceful shutdown o.e.j.s.ServletContextHandler{/,null}
INFO  [2015-01-05 06:52:04,530] org.eclipse.jetty.server.handler.ContextHandler: stopped o.e.j.s.ServletContextHandler{/,null}
INFO  [2015-01-05 06:52:04,530] org.eclipse.jetty.server.handler.ContextHandler: stopped o.e.j.s.ServletContextHandler{/,null}
15/01/05 12:22:05 WARN client.transport: [Firebrand] node [#transport#-1][Ashoks-MacBook-Pro.local][inet[/127.0.0.1:9300]] not part of the cluster Cluster [foxtrot], ignoring...
15/01/05 12:22:10 WARN client.transport: [Firebrand] node [#transport#-1][Ashoks-MacBook-Pro.local][inet[/127.0.0.1:9300]] not part of the cluster Cluster [foxtrot], ignoring...
15/01/05 12:22:15 WARN client.transport: [Firebrand] node [#transport#-1][Ashoks-MacBook-Pro.local][inet[/127.0.0.1:9300]] not part of the cluster Cluster [foxtrot], ignoring...
15/01/05 12:22:20 WARN client.transport: [Firebrand] node [#transport#-1][Ashoks-MacBook-Pro.local][inet[/127.0.0.1:9300]] not part of the cluster Cluster [foxtrot], ignoring...
15/01/05 12:22:25 WARN client.transport: [Firebrand] node [#transport#-1][Ashoks-MacBook-Pro.local][inet[/127.0.0.1:9300]] not part of the cluster Cluster [foxtrot], ignoring...
15/01/05 12:22:30 WARN client.transport: [Firebrand] node [#transport#-1][Ashoks-MacBook-Pro.local][inet[/127.0.0.1:9300]] not part of the cluster Cluster [foxtrot], ignoring...
15/01/05 12:22:35 WARN client.transport: [Firebrand] node [#transport#-1][Ashoks-MacBook-Pro.local][inet[/127.0.0.1:9300]] not part of the cluster Cluster [foxtrot], ignoring...
15/01/05 12:22:40 WARN client.transport: [Firebrand] node [#transport#-1][Ashoks-MacBook-Pro.local][inet[/127.0.0.1:9300]] not part of the cluster Cluster [foxtrot], ignoring...
15/01/05 12:22:45 WARN client.transport: [Firebrand] node [#transport#-1][Ashoks-MacBook-Pro.local][inet[/127.0.0.1:9300]] not part of the cluster Cluster [foxtrot], ignoring...
15/01/05 12:22:50 WARN client.transport: [Firebrand] node [#transport#-1][Ashoks-MacBook-Pro.local][inet[/127.0.0.1:9300]] not part of the cluster Cluster [foxtrot], ignoring...
15/01/05 12:22:55 WARN client.transport: [Firebrand] node [#transport#-1][Ashoks-MacBook-Pro.local][inet[/127.0.0.1:9300]] not part of the cluster Cluster [foxtrot], ignoring...
15/01/05 12:23:00 WARN client.transport: [Firebrand] node [#transport#-1][Ashoks-MacBook-Pro.local][inet[/127.0.0.1:9300]] not part of the cluster Cluster [foxtrot], ignoring...
15/01/05 12:23:05 WARN client.transport: [Firebrand] node [#transport#-1][Ashoks-MacBook-Pro.local][inet[/127.0.0.1:9300]] not part of the cluster Cluster [foxtrot], ignoring...
15/01/05 12:23:10 WARN client.transport: [Firebrand] node [#transport#-1][Ashoks-MacBook-Pro.local][inet[/127.0.0.1:9300]] not part of the cluster Cluster [foxtrot], ignoring...


It seems like foxtrot is expecting specific versions of elastic search and Hbase. Please mentioned the appropriate versions for the same. And after starting HBase and ES, do I need to create some tables manually (I only created foxtrot named table in Hbase)?


Thanks,
Ashish

**Comment by ashubhumca** [comment]
I've also tried it with Elasticsearch version 1.1.1 but still getting the above mentioned issue. Please help.

Thanks,
Ashish

**Comment by ashubhumca** [comment]
Thanks Santanu! That issue has been fixed and now I'm able to start the service.
But below command is giving me time out problem.

           ashish$ curl -H 'Content-type: application/json' -XPOST http://localhost:18000/foxtrot/v1/tables -d '{ "name" : "testapp", "ttl" : 7 }'

          {"error":"[table-meta][4] [2] shardIt, [1] active : Timeout waiting for [1m], request: index {[table-meta][table-meta][testapp], source[{\"name\":\"testapp\",\"ttl\":7}]}"}

Below is the log for the same:

INFO  [2015-01-05 08:41:33,355] com.flipkart.foxtrot.core.querystore.impl.DistributedTableMetadataManager: Saving Table : com.flipkart.foxtrot.common.Table@624c6693[name=testapp,ttl=7]
INFO  [2015-01-05 08:41:33,358] TableMapStore: Load called for: testapp
INFO  [2015-01-05 08:41:33,363] TableMapStore: Storing key: testapp
ERROR [2015-01-05 08:42:33,428] com.hazelcast.map.operation.PutOperation: [localhost]:5701 [foxtrot] [3.3.3] [table-meta][4] [2] shardIt, [1] active : Timeout waiting for [1m], request: index {[table-meta][table-meta][testapp], source[{"name":"testapp","ttl":7}]}
! org.elasticsearch.action.UnavailableShardsException: [table-meta][4] [2] shardIt, [1] active : Timeout waiting for [1m], request: index {[table-meta][table-meta][testapp], source[{"name":"testapp","ttl":7}]}
! at org.elasticsearch.action.support.replication.TransportShardReplicationOperationAction$AsyncShardOperationAction.raiseTimeoutFailure(TransportShardReplicationOperationAction.java:548) ~[foxtrot-server-0.1.jar:na]
! at org.elasticsearch.action.support.replication.TransportShardReplicationOperationAction$AsyncShardOperationAction$3.onTimeout(TransportShardReplicationOperationAction.java:538) ~[foxtrot-server-0.1.jar:na]
! at org.elasticsearch.cluster.service.InternalClusterService$NotifyTimeout.run(InternalClusterService.java:492) ~[foxtrot-server-0.1.jar:na]
! at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145) ~[na:1.7.0_71]
! at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615) ~[na:1.7.0_71]
! at java.lang.Thread.run(Thread.java:745) ~[na:1.7.0_71]
ERROR [2015-01-05 08:42:33,431] com.flipkart.foxtrot.server.resources.TableMetadataResource: Unable to save table com.flipkart.foxtrot.common.Table@624c6693[name=testapp,ttl=7]
! org.elasticsearch.action.UnavailableShardsException: [table-meta][4] [2] shardIt, [1] active : Timeout waiting for [1m], request: index {[table-meta][table-meta][testapp], source[{"name":"testapp","ttl":7}]}
! at org.elasticsearch.action.support.replication.TransportShardReplicationOperationAction$AsyncShardOperationAction.raiseTimeoutFailure(TransportShardReplicationOperationAction.java:548) ~[foxtrot-server-0.1.jar:na]
! at org.elasticsearch.action.support.replication.TransportShardReplicationOperationAction$AsyncShardOperationAction$3.onTimeout(TransportShardReplicationOperationAction.java:538) ~[foxtrot-server-0.1.jar:na]
! at org.elasticsearch.cluster.service.InternalClusterService$NotifyTimeout.run(InternalClusterService.java:492) ~[foxtrot-server-0.1.jar:na]
! at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145) ~[na:1.7.0_71]
! at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615) ~[na:1.7.0_71]
! at java.lang.Thread.run(Thread.java:745) ~[na:1.7.0_71]
ERROR [2015-01-05 08:42:33,434] com.sun.jersey.spi.container.ContainerResponse: Mapped exception to response: 500 (Internal Server Error)
! javax.ws.rs.WebApplicationException: null
! at com.flipkart.foxtrot.server.resources.TableMetadataResource.save(TableMetadataResource.java:47) ~[foxtrot-server-0.1.jar:na]
! at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.7.0_71]
! at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57) ~[na:1.7.0_71]
! at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.7.0_71]
! at java.lang.reflect.Method.invoke(Method.java:606) ~[na:1.7.0_71]
! at com.sun.jersey.spi.container.JavaMethodInvokerFactory$1.invoke(JavaMethodInvokerFactory.java:60) ~[foxtrot-server-0.1.jar:na]
! at com.sun.jersey.server.impl.model.method.dispatch.AbstractResourceMethodDispatchProvider$TypeOutInvoker._dispatch(AbstractResourceMethodDispatchProvider.java:185) ~[foxtrot-server-0.1.jar:na]
! at com.sun.jersey.server.impl.model.method.dispatch.ResourceJavaMethodDispatcher.dispatch(ResourceJavaMethodDispatcher.java:75) ~[foxtrot-server-0.1.jar:na]
! at com.yammer.dropwizard.jersey.OptionalResourceMethodDispatchAdapter$OptionalRequestDispatcher.dispatch(OptionalResourceMethodDispatchAdapter.java:37) ~[foxtrot-server-0.1.jar:na]
! at com.sun.jersey.server.impl.uri.rules.HttpMethodRule.accept(HttpMethodRule.java:302) ~[foxtrot-server-0.1.jar:na]
! at com.sun.jersey.server.impl.uri.rules.ResourceObjectRule.accept(ResourceObjectRule.java:100) ~[foxtrot-server-0.1.jar:na]
! at com.sun.jersey.server.impl.uri.rules.RightHandPathRule.accept(RightHandPathRule.java:147) ~[foxtrot-server-0.1.jar:na]
! at com.sun.jersey.server.impl.uri.rules.RootResourceClassesRule.accept(RootResourceClassesRule.java:84) ~[foxtrot-server-0.1.jar:na]
! at com.sun.jersey.server.impl.application.WebApplicationImpl._handleRequest(WebApplicationImpl.java:1511) [foxtrot-server-0.1.jar:na]
! at com.sun.jersey.server.impl.application.WebApplicationImpl._handleRequest(WebApplicationImpl.java:1442) [foxtrot-server-0.1.jar:na]
! at com.sun.jersey.server.impl.application.WebApplicationImpl.handleRequest(WebApplicationImpl.java:1391) [foxtrot-server-0.1.jar:na]
! at com.sun.jersey.server.impl.application.WebApplicationImpl.handleRequest(WebApplicationImpl.java:1381) [foxtrot-server-0.1.jar:na]
! at com.sun.jersey.spi.container.servlet.WebComponent.service(WebComponent.java:416) [foxtrot-server-0.1.jar:na]
! at com.sun.jersey.spi.container.servlet.ServletContainer.service(ServletContainer.java:538) [foxtrot-server-0.1.jar:na]
! at com.sun.jersey.spi.container.servlet.ServletContainer.service(ServletContainer.java:716) [foxtrot-server-0.1.jar:na]
! at javax.servlet.http.HttpServlet.service(HttpServlet.java:820) [foxtrot-server-0.1.jar:na]
! at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:669) [foxtrot-server-0.1.jar:na]
! at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1448) [foxtrot-server-0.1.jar:na]
! at org.eclipse.jetty.servlets.CrossOriginFilter.handle(CrossOriginFilter.java:247) [foxtrot-server-0.1.jar:na]
! at org.eclipse.jetty.servlets.CrossOriginFilter.doFilter(CrossOriginFilter.java:210) [foxtrot-server-0.1.jar:na]
! at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1419) [foxtrot-server-0.1.jar:na]
! at com.yammer.dropwizard.servlets.ThreadNameFilter.doFilter(ThreadNameFilter.java:29) [foxtrot-server-0.1.jar:na]
! at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1419) [foxtrot-server-0.1.jar:na]
! at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:455) [foxtrot-server-0.1.jar:na]
! at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1075) [foxtrot-server-0.1.jar:na]
! at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:384) [foxtrot-server-0.1.jar:na]
! at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1009) [foxtrot-server-0.1.jar:na]
! at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:135) [foxtrot-server-0.1.jar:na]
! at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:116) [foxtrot-server-0.1.jar:na]
! at com.yammer.metrics.jetty.InstrumentedHandler.handle(InstrumentedHandler.java:200) [foxtrot-server-0.1.jar:na]
! at org.eclipse.jetty.server.handler.GzipHandler.handle(GzipHandler.java:301) [foxtrot-server-0.1.jar:na]
! at com.yammer.dropwizard.jetty.BiDiGzipHandler.handle(BiDiGzipHandler.java:123) [foxtrot-server-0.1.jar:na]
! at org.eclipse.jetty.server.handler.HandlerCollection.handle(HandlerCollection.java:154) [foxtrot-server-0.1.jar:na]
! at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:116) [foxtrot-server-0.1.jar:na]
! at org.eclipse.jetty.server.Server.handle(Server.java:368) [foxtrot-server-0.1.jar:na]
! at org.eclipse.jetty.server.AbstractHttpConnection.handleRequest(AbstractHttpConnection.java:489) [foxtrot-server-0.1.jar:na]
! at org.eclipse.jetty.server.AbstractHttpConnection.content(AbstractHttpConnection.java:953) [foxtrot-server-0.1.jar:na]
! at org.eclipse.jetty.server.AbstractHttpConnection$RequestHandler.content(AbstractHttpConnection.java:1014) [foxtrot-server-0.1.jar:na]
! at org.eclipse.jetty.http.HttpParser.parseNext(HttpParser.java:861) [foxtrot-server-0.1.jar:na]
! at org.eclipse.jetty.http.HttpParser.parseAvailable(HttpParser.java:240) [foxtrot-server-0.1.jar:na]
! at org.eclipse.jetty.server.AsyncHttpConnection.handle(AsyncHttpConnection.java:82) [foxtrot-server-0.1.jar:na]
! at org.eclipse.jetty.io.nio.SelectChannelEndPoint.handle(SelectChannelEndPoint.java:628) [foxtrot-server-0.1.jar:na]
! at org.eclipse.jetty.io.nio.SelectChannelEndPoint$1.run(SelectChannelEndPoint.java:52) [foxtrot-server-0.1.jar:na]
! at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:608) [foxtrot-server-0.1.jar:na]
! at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:543) [foxtrot-server-0.1.jar:na]
! at java.lang.Thread.run(Thread.java:745) [na:1.7.0_71]
0:0:0:0:0:0:0:1 - - [05/Jan/2015:08:41:33 +0000] "POST /foxtrot/v1/tables HTTP/1.1" 500 172 60129 60129





Please look into it.

Regards,
Ashish

**Comment by santanusinha** [comment]
How many nodes do you have on your ES cluster? Create the "table-meta" index. Looks like you replica settings are not proper. Check below:

curl -XPUT 'http://<es-host>:9200/table-meta/' -d '{
    "settings" : {
        "index" : {
            "number_of_shards" : 5,
            "number_of_replicas" : 0 //Set this to number of hosts on ES cluster -1 (0 for local)
        }
    }
}'

**Comment by santanusinha** [comment]
Also, do a git pull, and rerun:

scripts/local_es_setup.sh localhost

I have changed the replication setup to be more localhost friendly.

- SS

**Comment by ashubhumca** [comment]
I'm using single node instance of elasticsearch and HBase in local mode  (POC phase) :-)
Now, it's working for me. I'm able to create a table. 
And I'll let you know in case of further hiccups/bugs.

Where can I get the end-to-end architecture of the application?

Thanks!

-Ashish

**Comment by santanusinha** [comment]
Planning to do a blogpost to explain the architecture. Please don't forget to put up feature and pull requests. Closing this issue. Reopen if you find any issue.

**Comment by santanusinha** [comment]
Closing...
